services:
  dosbox-anywhere:
    image: ghcr.io/ggaspari/dosbox-anywhere:latest
    platform: linux/amd64
    container_name: dosbox-anywhere
    network_mode: host
    ipc: host
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
      - MKNOD
    device_cgroup_rules:
      - 'c 13:* rmw'
    devices:
      - /dev/dri:/dev/dri
      - /dev/uinput:/dev/uinput
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - RENDER_GID=${RENDER_GID:-}
    volumes:
      - ${CONFIG_DIR:-./dockerdata/dosbox-anywhere}:/config
      - ${GAMES_DIR:-./games}:/games
      - /dev/input:/dev/input
    restart: unless-stopped
